/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Dominio.Cliente;
import Dominio.Cuenta;
import Excepciones.PersistenciaException;
import Interfaces.IClientesDAO;
import Interfaces.ICuentasDAO;
import Interfaces.IDireccionDAO;
import Utils.Validadores;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ildex
 */
public class Operaciones extends javax.swing.JFrame {
    
    private final IClientesDAO clientesDAO;
    private final IDireccionDAO direccionDAO;
    private final ICuentasDAO cuentasDAO;
    private final String correo;
    private final Validadores validadores = new Validadores();
    private int xMouse;
    private int yMouse;
    
    /**
     * Creates new form Operaciones
     * @param clientesDAO
     * @param direccionDAO
     * @param correo
     * @param cuentasDAO
     */
    public Operaciones(IClientesDAO clientesDAO, IDireccionDAO direccionDAO, String correo, ICuentasDAO cuentasDAO) throws PersistenciaException {
        this.clientesDAO = clientesDAO;
        this.direccionDAO = direccionDAO;
        this.correo = correo;
        this.cuentasDAO = cuentasDAO;
        initComponents();
        Cliente clienteLogueado = this.clientesDAO.consultar(correo);
        lblCliente.setText("Cliente: "+clienteLogueado.getNombre()+(" ")+clienteLogueado.getApellidoPaterno()+(" ")+clienteLogueado.getApellidoMaterno());
        System.out.println(clienteLogueado.getIdCliente());
        cbxCuentas.setVisible(false);
        btnCrear.setVisible(false);
    }
    
    public void crearCuenta(){
        try {
            Cliente clienteLogueado = this.clientesDAO.consultar(correo);
            Cuenta cuentaCreada = this.cuentasDAO.insertar(clienteLogueado.getIdCliente());
            System.out.println(clienteLogueado.getIdCliente());
        } catch (PersistenciaException e) {
            this.mostrarMensajeErrorCuentaCreada();
        }
    }
    
    private void mostrarMensajeErrorCuentaCreada() {
        JOptionPane.showMessageDialog(this, "No fue posible crear una cuenta", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JPanel();
        lblRegresar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        barraIzq = new javax.swing.JPanel();
        btnRetiro = new javax.swing.JPanel();
        lblRetiro = new javax.swing.JLabel();
        btnDeposito = new javax.swing.JPanel();
        lblDeposito = new javax.swing.JLabel();
        btnTransferencia = new javax.swing.JPanel();
        lblTransferencia = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCuenta = new javax.swing.JPanel();
        lblCuenta = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        barraTop = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();
        lblKk = new javax.swing.JLabel();
        panelTransferencia = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        panelDeposito = new javax.swing.JPanel();
        lblKk1 = new javax.swing.JLabel();
        panelRetiro = new javax.swing.JPanel();
        lblKk2 = new javax.swing.JLabel();
        panelCuenta = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCrear = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        cbxCuentas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });

        lblRegresar.setText("<");
        lblRegresar.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegresarMouseEntered(evt);
            }
        });
        btnRegresar.add(lblRegresar);

        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });

        lblX.setText("X");
        lblX.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        btnSalir.add(lblX);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 760, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        barraIzq.setBackground(new java.awt.Color(102, 102, 255));
        barraIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetiro.setBackground(new java.awt.Color(102, 102, 255));
        btnRetiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblRetiro.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        lblRetiro.setForeground(new java.awt.Color(255, 255, 255));
        lblRetiro.setText("Retiro");

        javax.swing.GroupLayout btnRetiroLayout = new javax.swing.GroupLayout(btnRetiro);
        btnRetiro.setLayout(btnRetiroLayout);
        btnRetiroLayout.setHorizontalGroup(
            btnRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRetiroLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblRetiro)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        btnRetiroLayout.setVerticalGroup(
            btnRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRetiroLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblRetiro)
                .addContainerGap())
        );

        barraIzq.add(btnRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 160, 50));

        btnDeposito.setBackground(new java.awt.Color(102, 102, 255));
        btnDeposito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblDeposito.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        lblDeposito.setForeground(new java.awt.Color(255, 255, 255));
        lblDeposito.setText("Deposito");

        javax.swing.GroupLayout btnDepositoLayout = new javax.swing.GroupLayout(btnDeposito);
        btnDeposito.setLayout(btnDepositoLayout);
        btnDepositoLayout.setHorizontalGroup(
            btnDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDepositoLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(lblDeposito)
                .addGap(42, 42, 42))
        );
        btnDepositoLayout.setVerticalGroup(
            btnDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDepositoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeposito)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        barraIzq.add(btnDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 160, 50));

        btnTransferencia.setBackground(new java.awt.Color(102, 102, 255));
        btnTransferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblTransferencia.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        lblTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        lblTransferencia.setText("Transferencia");

        javax.swing.GroupLayout btnTransferenciaLayout = new javax.swing.GroupLayout(btnTransferencia);
        btnTransferencia.setLayout(btnTransferenciaLayout);
        btnTransferenciaLayout.setHorizontalGroup(
            btnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTransferenciaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnTransferenciaLayout.setVerticalGroup(
            btnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTransferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTransferencia)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        barraIzq.add(btnTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 50));
        barraIzq.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, 10));

        btnCuenta.setBackground(new java.awt.Color(102, 102, 255));
        btnCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCuentaMouseClicked(evt);
            }
        });

        lblCuenta.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblCuenta.setText("Cuenta");

        javax.swing.GroupLayout btnCuentaLayout = new javax.swing.GroupLayout(btnCuenta);
        btnCuenta.setLayout(btnCuentaLayout);
        btnCuentaLayout.setHorizontalGroup(
            btnCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCuentaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblCuenta)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        btnCuentaLayout.setVerticalGroup(
            btnCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCuenta)
                .addGap(34, 34, 34))
        );

        barraIzq.add(btnCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 50));
        barraIzq.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 10));
        barraIzq.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, 10));
        barraIzq.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 140, 10));

        getContentPane().add(barraIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 500));

        barraTop.setBackground(new java.awt.Color(204, 204, 255));

        lblCliente.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Editar Cliente");

        javax.swing.GroupLayout barraTopLayout = new javax.swing.GroupLayout(barraTop);
        barraTop.setLayout(barraTopLayout);
        barraTopLayout.setHorizontalGroup(
            barraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(88, 88, 88))
        );
        barraTopLayout.setVerticalGroup(
            barraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraTopLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(barraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        getContentPane().add(barraTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 120));

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));

        lblKk.setFont(new java.awt.Font("Eras Medium ITC", 0, 48)); // NOI18N
        lblKk.setForeground(new java.awt.Color(0, 0, 0));
        lblKk.setText("Contenido");

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(lblKk)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblKk)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        getContentPane().add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 680, 500));

        panelTransferencia.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo1.setFont(new java.awt.Font("Eras Medium ITC", 0, 48)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo1.setText("Transferencia");

        javax.swing.GroupLayout panelTransferenciaLayout = new javax.swing.GroupLayout(panelTransferencia);
        panelTransferencia.setLayout(panelTransferenciaLayout);
        panelTransferenciaLayout.setHorizontalGroup(
            panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferenciaLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(lblTitulo1)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        panelTransferenciaLayout.setVerticalGroup(
            panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferenciaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitulo1)
                .addContainerGap(432, Short.MAX_VALUE))
        );

        getContentPane().add(panelTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 680, 520));

        panelDeposito.setBackground(new java.awt.Color(255, 255, 255));

        lblKk1.setFont(new java.awt.Font("Eras Medium ITC", 0, 48)); // NOI18N
        lblKk1.setForeground(new java.awt.Color(0, 0, 0));
        lblKk1.setText("Deposito");

        javax.swing.GroupLayout panelDepositoLayout = new javax.swing.GroupLayout(panelDeposito);
        panelDeposito.setLayout(panelDepositoLayout);
        panelDepositoLayout.setHorizontalGroup(
            panelDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepositoLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(lblKk1)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        panelDepositoLayout.setVerticalGroup(
            panelDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepositoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblKk1)
                .addContainerGap(432, Short.MAX_VALUE))
        );

        getContentPane().add(panelDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 680, 520));

        panelRetiro.setBackground(new java.awt.Color(255, 255, 255));

        lblKk2.setFont(new java.awt.Font("Eras Medium ITC", 0, 48)); // NOI18N
        lblKk2.setForeground(new java.awt.Color(0, 0, 0));
        lblKk2.setText("Retiro");

        javax.swing.GroupLayout panelRetiroLayout = new javax.swing.GroupLayout(panelRetiro);
        panelRetiro.setLayout(panelRetiroLayout);
        panelRetiroLayout.setHorizontalGroup(
            panelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRetiroLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(lblKk2)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        panelRetiroLayout.setVerticalGroup(
            panelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRetiroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblKk2)
                .addContainerGap(432, Short.MAX_VALUE))
        );

        getContentPane().add(panelRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 680, 520));

        panelCuenta.setBackground(new java.awt.Color(255, 255, 255));
        panelCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Eras Medium ITC", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Cuenta");
        panelCuenta.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 12, -1, -1));

        btnCrear.setBackground(new java.awt.Color(51, 102, 255));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
        });

        lblRegistrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setText("NUEVA CUENTA");
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCrearLayout = new javax.swing.GroupLayout(btnCrear);
        btnCrear.setLayout(btnCrearLayout);
        btnCrearLayout.setHorizontalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearLayout.createSequentialGroup()
                .addComponent(lblRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnCrearLayout.setVerticalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        panelCuenta.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 60));

        cbxCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelCuenta.add(cbxCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, -1));

        getContentPane().add(panelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 680, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegresarMouseEntered

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        inicio in = new inicio(clientesDAO, direccionDAO, cuentasDAO);
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
        btnRegresar.setBackground(Color.gray);
        lblRegresar.setForeground(Color.white);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        btnRegresar.setBackground(new Color(238, 238, 238));
        lblRegresar.setForeground(Color.black);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        btnSalir.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        btnSalir.setBackground(new Color(238, 238, 238));
        lblX.setForeground(Color.black);
    }//GEN-LAST:event_btnSalirMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuentaMouseClicked
        // TODO add your handling code here:
        panelCuenta.setVisible(true);
        cbxCuentas.setVisible(true);
        btnCrear.setVisible(true);
        panelContenido.setVisible(false);
        panelTransferencia.setVisible(false);
        panelDeposito.setVisible(false);
        panelRetiro.setVisible(false);
    }//GEN-LAST:event_btnCuentaMouseClicked

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        // TODO add your handling code here:
        crearCuenta();
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseEntered
        // TODO add your handling code here:
        btnCrear.setBackground(new Color(98, 137, 255));
    }//GEN-LAST:event_lblRegistrarMouseEntered

    private void lblRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseExited
        // TODO add your handling code here:
        btnCrear.setBackground(new Color(32, 92, 255));
    }//GEN-LAST:event_lblRegistrarMouseExited

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered

    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited

    }//GEN-LAST:event_btnCrearMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Operaciones().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraIzq;
    private javax.swing.JPanel barraTop;
    private javax.swing.JPanel btnCrear;
    private javax.swing.JPanel btnCuenta;
    private javax.swing.JPanel btnDeposito;
    private javax.swing.JPanel btnRegresar;
    private javax.swing.JPanel btnRetiro;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel btnTransferencia;
    private javax.swing.JComboBox<String> cbxCuentas;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblDeposito;
    private javax.swing.JLabel lblKk;
    private javax.swing.JLabel lblKk1;
    private javax.swing.JLabel lblKk2;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblRetiro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTransferencia;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelCuenta;
    private javax.swing.JPanel panelDeposito;
    private javax.swing.JPanel panelRetiro;
    private javax.swing.JPanel panelTransferencia;
    // End of variables declaration//GEN-END:variables
}
