/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Dominio.Retiro;
import Excepciones.PersistenciaException;
import Interfaces.IClientesDAO;
import Interfaces.ICuentasDAO;
import Interfaces.IDireccionDAO;
import Interfaces.IRetirosDAO;
import Interfaces.ITransferenciasDAO;
import Utils.Validadores;
import implementaciones.CuentasDAO;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ildex
 */
public class retiroSinCliente extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(CuentasDAO.class.getName());
    private final IClientesDAO clientesDAO;
    private final IDireccionDAO direccionDAO;
    private final ICuentasDAO cuentasDAO;
    private final ITransferenciasDAO transferenciasDAO;
    private final IRetirosDAO retirosDAO;
    private final String correo;
    private final Validadores validadores = new Validadores();
    private int xMouse;
    private int yMouse;

    public retiroSinCliente(IClientesDAO clientesDAO, IDireccionDAO direccionDAO, String correo, ICuentasDAO cuentasDAO, ITransferenciasDAO transferenciasDAO, IRetirosDAO retirosDAO) throws PersistenciaException {
        this.clientesDAO = clientesDAO;
        this.direccionDAO = direccionDAO;
        this.correo = correo;
        this.cuentasDAO = cuentasDAO;
        this.transferenciasDAO = transferenciasDAO;
        this.retirosDAO = retirosDAO;
        initComponents();
        panelRetiroV();
    }

    private void panelRetiroV() {
        //Panel Retiro
        lblKk2.setVisible(true);
        txtFolio.setVisible(true);
        lblFolio.setVisible(true);
        jSp3.setVisible(true);
        lblContrasena.setVisible(true);
        jSp4.setVisible(true);
        btnRetirar.setVisible(true);
        lblRetirar.setVisible(true);
        txtPass.setVisible(true);
    }

    private void limpiarTxtRetiro() {
        txtFolio.setText("");
        txtPass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JPanel();
        lblRegresar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        barraIzq = new javax.swing.JPanel();
        btnRetiroT = new javax.swing.JPanel();
        lblRetiro = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        barraTop = new javax.swing.JPanel();
        panelRetiro = new javax.swing.JPanel();
        lblKk2 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        lblFolio = new javax.swing.JLabel();
        jSp3 = new javax.swing.JSeparator();
        lblContrasena = new javax.swing.JLabel();
        jSp4 = new javax.swing.JSeparator();
        btnRetirar = new javax.swing.JPanel();
        lblRetirar = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });

        lblRegresar.setText("<");
        lblRegresar.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegresarMouseEntered(evt);
            }
        });
        btnRegresar.add(lblRegresar);

        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });

        lblX.setText("X");
        lblX.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        btnSalir.add(lblX);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 760, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        barraIzq.setBackground(new java.awt.Color(102, 102, 255));
        barraIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetiroT.setBackground(new java.awt.Color(102, 102, 255));
        btnRetiroT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetiroT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetiroTMouseClicked(evt);
            }
        });

        lblRetiro.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        lblRetiro.setForeground(new java.awt.Color(255, 255, 255));
        lblRetiro.setText("Retiro");

        javax.swing.GroupLayout btnRetiroTLayout = new javax.swing.GroupLayout(btnRetiroT);
        btnRetiroT.setLayout(btnRetiroTLayout);
        btnRetiroTLayout.setHorizontalGroup(
            btnRetiroTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRetiroTLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblRetiro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRetiroTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnRetiroTLayout.setVerticalGroup(
            btnRetiroTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRetiroTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRetiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        barraIzq.add(btnRetiroT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 50));

        getContentPane().add(barraIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 500));

        barraTop.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout barraTopLayout = new javax.swing.GroupLayout(barraTop);
        barraTop.setLayout(barraTopLayout);
        barraTopLayout.setHorizontalGroup(
            barraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        barraTopLayout.setVerticalGroup(
            barraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(barraTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 120));

        panelRetiro.setBackground(new java.awt.Color(255, 255, 255));
        panelRetiro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKk2.setFont(new java.awt.Font("Eras Medium ITC", 0, 48)); // NOI18N
        lblKk2.setForeground(new java.awt.Color(0, 0, 0));
        lblKk2.setText("Retiro");
        panelRetiro.add(lblKk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        txtFolio.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        txtFolio.setBorder(null);
        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFolioKeyTyped(evt);
            }
        });
        panelRetiro.add(txtFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 130, 16));

        lblFolio.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblFolio.setForeground(new java.awt.Color(0, 0, 0));
        lblFolio.setText("Folio");
        panelRetiro.add(lblFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 80, -1));

        jSp3.setForeground(new java.awt.Color(0, 0, 0));
        panelRetiro.add(jSp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 130, 10));

        lblContrasena.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena.setText("Contraseña");
        panelRetiro.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jSp4.setForeground(new java.awt.Color(0, 0, 0));
        panelRetiro.add(jSp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 130, 10));

        btnRetirar.setBackground(new java.awt.Color(51, 102, 255));
        btnRetirar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepositar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDepositar1MouseExited(evt);
            }
        });

        lblRetirar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblRetirar.setForeground(new java.awt.Color(255, 255, 255));
        lblRetirar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetirar.setText("RETIRAR");
        lblRetirar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblRetirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDepositar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDepositar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDepositar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRetirarLayout = new javax.swing.GroupLayout(btnRetirar);
        btnRetirar.setLayout(btnRetirarLayout);
        btnRetirarLayout.setHorizontalGroup(
            btnRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRetirarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblRetirar)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        btnRetirarLayout.setVerticalGroup(
            btnRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRetirarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRetiro.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 210, 60));

        txtPass.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        txtPass.setBorder(null);
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });
        panelRetiro.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 130, -1));

        getContentPane().add(panelRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 680, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegresarMouseEntered

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        inicio in = new inicio(clientesDAO, direccionDAO, cuentasDAO, transferenciasDAO, retirosDAO);
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
        btnRegresar.setBackground(Color.gray);
        lblRegresar.setForeground(Color.white);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        btnRegresar.setBackground(new Color(238, 238, 238));
        lblRegresar.setForeground(Color.black);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        btnSalir.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        btnSalir.setBackground(new Color(238, 238, 238));
        lblX.setForeground(Color.black);
    }//GEN-LAST:event_btnSalirMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed

    }//GEN-LAST:event_headerMousePressed

    private void btnRetiroTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetiroTMouseClicked

    }//GEN-LAST:event_btnRetiroTMouseClicked

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < ',' || car > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPassKeyTyped

    private void btnDepositar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositar1MouseExited

    }//GEN-LAST:event_btnDepositar1MouseExited

    private void btnDepositar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositar1MouseEntered

    }//GEN-LAST:event_btnDepositar1MouseEntered

    private void btnRetirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarMouseClicked
        // TODO add your handling code here:
        if (!validadores.esVacia(txtFolio.getText())) {
            JOptionPane.showMessageDialog(this, "Campo de folio vacío", "Error", 0);
        } else if (!validadores.esVacia(txtPass.getText())) {
            JOptionPane.showMessageDialog(this, "Campo de contraseña vacío", "Error", 0);
        } else {
            try {
                int folio = Integer.parseInt(txtFolio.getText());
                String contra = txtPass.getText();
                Date fechaActual = new Date();
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy/MM/dd");
                String fechaA = formatoFecha.format(fechaActual);
                String es = "cobrado";
                this.retirosDAO.actualizar(folio, contra, fechaA);
                this.retirosDAO.actualizarEstado(folio, contra, es);
                if (this.retirosDAO.actualizar(folio, contra, fechaA) == true) {
                    Retiro cuenta = this.retirosDAO.consultarCuenta(folio);
                    this.cuentasDAO.actualizarDescMonto(cuenta.getIdCuenta(), cuenta.getMonto());
                    JOptionPane.showMessageDialog(this, "Retiro satisfactorio", "LuluAdmin", 1);
                    limpiarTxtRetiro();
                }
            } catch (PersistenciaException ex) {
                Logger.getLogger(retiroSinCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRetirarMouseClicked

    private void lblDepositar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDepositar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDepositar1MouseExited

    private void lblDepositar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDepositar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDepositar1MouseEntered

    private void lblDepositar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDepositar1MouseClicked

    }//GEN-LAST:event_lblDepositar1MouseClicked

    private void txtFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < ',' || car > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFolioKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraIzq;
    private javax.swing.JPanel barraTop;
    private javax.swing.JPanel btnRegresar;
    private javax.swing.JPanel btnRetirar;
    private javax.swing.JPanel btnRetiroT;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSp3;
    private javax.swing.JSeparator jSp4;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblKk2;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblRetirar;
    private javax.swing.JLabel lblRetiro;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel panelRetiro;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
